import "./globals.css";
import localFont from "next/font/local";

const euclid = localFont({
  src: [
    {
      path: "./fonts/EuclidFlex-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/EuclidFlex-Medium.ttf",
      weight: "500",
    },
    {
      path: "./fonts/EuclidFlex-Bold.ttf",
      weight: "700",
    },
  ],
  display: "swap",
  variable: "--font-euclid",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${euclid.variable}`}>
      <body className="flex justify-center bg-white">
        <div id="modal"></div>
        <div className="m-w-4xl min-h-screen w-3/5 bg-white px-12 shadow-xl">
          {children}
        </div>
      </body>
    </html>
  );
}
